apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-app
          image: timshee/todo-django-app:0.1.3
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SECRET_KEY
              value: "your_secret_key_here"
            # Other Django environment variables if needed
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              value: "django_db"
            - name: POSTGRES_USER
              value: "your_postgres_user"
            - name: POSTGRES_PASSWORD
              value: "your_postgres_password"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: django-app-service
spec:
  selector:
    app: django-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
